
SECRET_KEY = 'YOUR_SECRET_KEY'

CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_REDIS_HOST': 'YOUR_REDIS_ENDPOINT',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 0,  
}

FILTER_STATE_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_REDIS_HOST': 'YOUR_REDIS_ENDPOINT',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 0,
}

EXPLORE_FORM_DATA_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_REDIS_HOST': 'YOUR_REDIS_ENDPOINT',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 0,
}

DATA_CACHE_CONFIG = {
    'CACHE_TYPE': 'redis',
    'CACHE_REDIS_HOST': 'YOUR_REDIS_ENDPOINT',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 0,
}